site_name: tky2240/cdk-for-dnscontrol
repo_url: https://github.com/tky2240/cdk-for-dnscontrol
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: light mode

nav:
  - CDK for dnscontrol: index.md
  - API Docs:
      - CLI: cli.md
      - CDK: 
          - Constructs:
              - cdk/constructs/app.md
              - cdk/constructs/dnscontrol-stack.md
              - cdk/constructs/dnscontrol-domain.md
          - Functions: cdk/functions/index.md

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: false
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      pygments_style: material
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
