"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DnscontrolUrl301Record = exports.DnscontrolUrlRecord = exports.DnscontrolTxtRecord = exports.DnscontrolTlsaRecord = exports.DnscontrolSvcbRecord = exports.DnscontrolSshfpRecord = exports.DnscontrolSrvRecord = exports.DnscontrolSoaRecord = exports.DnscontrolR53AliasRecord = exports.DnscontrolPtrRecord = exports.DnscontrolPorkbunUrlfwdRecord = exports.DnscontrolNsRecord = exports.DnscontrolNaptrRecord = exports.DnscontrolMxRecord = exports.DnscontrolHttpsRecord = exports.DnscontrolFrameRecord = exports.DnscontrolDsRecord = exports.DnscontrolDnskeyRecord = exports.DnscontrolDnameRecord = exports.DnscontrolDhcidRecord = exports.DnscontrolCnameRecord = exports.DnscontrolCloudnsWrRecord = exports.DnscontrolCfWorkerRouteRecord = exports.DnscontrolCfTempRedirectRecord = exports.DnscontrolCfRedirectRecord = exports.DnscontrolCaaRecord = exports.DnscontrolBunnyDnsRdrRecord = exports.DnscontrolAzureAliasRecord = exports.DnscontrolAliasRecord = exports.DnscontrolAAAARecord = exports.DnscontrolARecord = void 0;
var a_1 = require("./a");
Object.defineProperty(exports, "DnscontrolARecord", { enumerable: true, get: function () { return a_1.DnscontrolARecord; } });
var aaaa_1 = require("./aaaa");
Object.defineProperty(exports, "DnscontrolAAAARecord", { enumerable: true, get: function () { return aaaa_1.DnscontrolAAAARecord; } });
var alias_1 = require("./alias");
Object.defineProperty(exports, "DnscontrolAliasRecord", { enumerable: true, get: function () { return alias_1.DnscontrolAliasRecord; } });
var azure_alias_1 = require("./azure-alias");
Object.defineProperty(exports, "DnscontrolAzureAliasRecord", { enumerable: true, get: function () { return azure_alias_1.DnscontrolAzureAliasRecord; } });
var bunny_dns_rdr_1 = require("./bunny-dns-rdr");
Object.defineProperty(exports, "DnscontrolBunnyDnsRdrRecord", { enumerable: true, get: function () { return bunny_dns_rdr_1.DnscontrolBunnyDnsRdrRecord; } });
var caa_1 = require("./caa");
Object.defineProperty(exports, "DnscontrolCaaRecord", { enumerable: true, get: function () { return caa_1.DnscontrolCaaRecord; } });
var cf_redirect_1 = require("./cf-redirect");
Object.defineProperty(exports, "DnscontrolCfRedirectRecord", { enumerable: true, get: function () { return cf_redirect_1.DnscontrolCfRedirectRecord; } });
var cf_temp_redirect_1 = require("./cf-temp-redirect");
Object.defineProperty(exports, "DnscontrolCfTempRedirectRecord", { enumerable: true, get: function () { return cf_temp_redirect_1.DnscontrolCfTempRedirectRecord; } });
var cf_worker_route_1 = require("./cf-worker-route");
Object.defineProperty(exports, "DnscontrolCfWorkerRouteRecord", { enumerable: true, get: function () { return cf_worker_route_1.DnscontrolCfWorkerRouteRecord; } });
var cloudns_wr_1 = require("./cloudns-wr");
Object.defineProperty(exports, "DnscontrolCloudnsWrRecord", { enumerable: true, get: function () { return cloudns_wr_1.DnscontrolCloudnsWrRecord; } });
var cname_1 = require("./cname");
Object.defineProperty(exports, "DnscontrolCnameRecord", { enumerable: true, get: function () { return cname_1.DnscontrolCnameRecord; } });
var dhcid_1 = require("./dhcid");
Object.defineProperty(exports, "DnscontrolDhcidRecord", { enumerable: true, get: function () { return dhcid_1.DnscontrolDhcidRecord; } });
var dname_1 = require("./dname");
Object.defineProperty(exports, "DnscontrolDnameRecord", { enumerable: true, get: function () { return dname_1.DnscontrolDnameRecord; } });
var dnskey_1 = require("./dnskey");
Object.defineProperty(exports, "DnscontrolDnskeyRecord", { enumerable: true, get: function () { return dnskey_1.DnscontrolDnskeyRecord; } });
var ds_1 = require("./ds");
Object.defineProperty(exports, "DnscontrolDsRecord", { enumerable: true, get: function () { return ds_1.DnscontrolDsRecord; } });
var frame_1 = require("./frame");
Object.defineProperty(exports, "DnscontrolFrameRecord", { enumerable: true, get: function () { return frame_1.DnscontrolFrameRecord; } });
var https_1 = require("./https");
Object.defineProperty(exports, "DnscontrolHttpsRecord", { enumerable: true, get: function () { return https_1.DnscontrolHttpsRecord; } });
// export { DnscontrolLocRecord } from "./loc"; // not implemented yet
var mx_1 = require("./mx");
Object.defineProperty(exports, "DnscontrolMxRecord", { enumerable: true, get: function () { return mx_1.DnscontrolMxRecord; } });
var naptr_1 = require("./naptr");
Object.defineProperty(exports, "DnscontrolNaptrRecord", { enumerable: true, get: function () { return naptr_1.DnscontrolNaptrRecord; } });
var ns_1 = require("./ns");
Object.defineProperty(exports, "DnscontrolNsRecord", { enumerable: true, get: function () { return ns_1.DnscontrolNsRecord; } });
var porkbun_urlfwd_1 = require("./porkbun-urlfwd");
Object.defineProperty(exports, "DnscontrolPorkbunUrlfwdRecord", { enumerable: true, get: function () { return porkbun_urlfwd_1.DnscontrolPorkbunUrlfwdRecord; } });
var ptr_1 = require("./ptr");
Object.defineProperty(exports, "DnscontrolPtrRecord", { enumerable: true, get: function () { return ptr_1.DnscontrolPtrRecord; } });
var r53_alias_1 = require("./r53-alias");
Object.defineProperty(exports, "DnscontrolR53AliasRecord", { enumerable: true, get: function () { return r53_alias_1.DnscontrolR53AliasRecord; } });
var soa_1 = require("./soa");
Object.defineProperty(exports, "DnscontrolSoaRecord", { enumerable: true, get: function () { return soa_1.DnscontrolSoaRecord; } });
var srv_1 = require("./srv");
Object.defineProperty(exports, "DnscontrolSrvRecord", { enumerable: true, get: function () { return srv_1.DnscontrolSrvRecord; } });
var sshfp_1 = require("./sshfp");
Object.defineProperty(exports, "DnscontrolSshfpRecord", { enumerable: true, get: function () { return sshfp_1.DnscontrolSshfpRecord; } });
var svcb_1 = require("./svcb");
Object.defineProperty(exports, "DnscontrolSvcbRecord", { enumerable: true, get: function () { return svcb_1.DnscontrolSvcbRecord; } });
var tlsa_1 = require("./tlsa");
Object.defineProperty(exports, "DnscontrolTlsaRecord", { enumerable: true, get: function () { return tlsa_1.DnscontrolTlsaRecord; } });
var txt_1 = require("./txt");
Object.defineProperty(exports, "DnscontrolTxtRecord", { enumerable: true, get: function () { return txt_1.DnscontrolTxtRecord; } });
var url_1 = require("./url");
Object.defineProperty(exports, "DnscontrolUrlRecord", { enumerable: true, get: function () { return url_1.DnscontrolUrlRecord; } });
var url301_1 = require("./url301");
Object.defineProperty(exports, "DnscontrolUrl301Record", { enumerable: true, get: function () { return url301_1.DnscontrolUrl301Record; } });
