"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IGNORE = exports.URL301 = exports.URL = exports.TXT = exports.TLSA = exports.SVCB = exports.SSHFP = exports.SRV = exports.SOA = exports.R53_ALIAS = exports.PTR = exports.PORKBUN_URLFWD = exports.NS = exports.NAPTR = exports.MX = exports.LOC = exports.HTTPS = exports.FRAME = exports.DS = exports.DNSKEY = exports.DNAME = exports.DHCID = exports.CNAME = exports.CF_WORKER_ROUTE = exports.CF_TEMP_REDIRECT = exports.CF_SINGLE_REDIRECT = exports.CF_REDIRECT = exports.CAA = exports.BUNNY_DNS_RDR = exports.AZURE_ALIAS = exports.ALIAS = exports.AKAMAI_CDN = exports.AAAA = exports.A = void 0;
var a_1 = require("./a");
Object.defineProperty(exports, "A", { enumerable: true, get: function () { return a_1.A; } });
var aaaa_1 = require("./aaaa");
Object.defineProperty(exports, "AAAA", { enumerable: true, get: function () { return aaaa_1.AAAA; } });
var akamai_cdn_1 = require("./akamai-cdn");
Object.defineProperty(exports, "AKAMAI_CDN", { enumerable: true, get: function () { return akamai_cdn_1.AKAMAI_CDN; } });
var alias_1 = require("./alias");
Object.defineProperty(exports, "ALIAS", { enumerable: true, get: function () { return alias_1.ALIAS; } });
var azure_alias_1 = require("./azure-alias");
Object.defineProperty(exports, "AZURE_ALIAS", { enumerable: true, get: function () { return azure_alias_1.AZURE_ALIAS; } });
var bunny_dns_rdr_1 = require("./bunny-dns-rdr");
Object.defineProperty(exports, "BUNNY_DNS_RDR", { enumerable: true, get: function () { return bunny_dns_rdr_1.BUNNY_DNS_RDR; } });
var caa_1 = require("./caa");
Object.defineProperty(exports, "CAA", { enumerable: true, get: function () { return caa_1.CAA; } });
var cf_redirect_1 = require("./cf-redirect");
Object.defineProperty(exports, "CF_REDIRECT", { enumerable: true, get: function () { return cf_redirect_1.CF_REDIRECT; } });
var cf_single_redirect_1 = require("./cf-single-redirect");
Object.defineProperty(exports, "CF_SINGLE_REDIRECT", { enumerable: true, get: function () { return cf_single_redirect_1.CF_SINGLE_REDIRECT; } });
var cf_temp_redirect_1 = require("./cf-temp-redirect");
Object.defineProperty(exports, "CF_TEMP_REDIRECT", { enumerable: true, get: function () { return cf_temp_redirect_1.CF_TEMP_REDIRECT; } });
var cf_worker_route_1 = require("./cf-worker-route");
Object.defineProperty(exports, "CF_WORKER_ROUTE", { enumerable: true, get: function () { return cf_worker_route_1.CF_WORKER_ROUTE; } });
var cname_1 = require("./cname");
Object.defineProperty(exports, "CNAME", { enumerable: true, get: function () { return cname_1.CNAME; } });
var dhcid_1 = require("./dhcid");
Object.defineProperty(exports, "DHCID", { enumerable: true, get: function () { return dhcid_1.DHCID; } });
var dname_1 = require("./dname");
Object.defineProperty(exports, "DNAME", { enumerable: true, get: function () { return dname_1.DNAME; } });
var dnskey_1 = require("./dnskey");
Object.defineProperty(exports, "DNSKEY", { enumerable: true, get: function () { return dnskey_1.DNSKEY; } });
var ds_1 = require("./ds");
Object.defineProperty(exports, "DS", { enumerable: true, get: function () { return ds_1.DS; } });
var frame_1 = require("./frame");
Object.defineProperty(exports, "FRAME", { enumerable: true, get: function () { return frame_1.FRAME; } });
var https_1 = require("./https");
Object.defineProperty(exports, "HTTPS", { enumerable: true, get: function () { return https_1.HTTPS; } });
var loc_1 = require("./loc");
Object.defineProperty(exports, "LOC", { enumerable: true, get: function () { return loc_1.LOC; } });
var mx_1 = require("./mx");
Object.defineProperty(exports, "MX", { enumerable: true, get: function () { return mx_1.MX; } });
var naptr_1 = require("./naptr");
Object.defineProperty(exports, "NAPTR", { enumerable: true, get: function () { return naptr_1.NAPTR; } });
var ns_1 = require("./ns");
Object.defineProperty(exports, "NS", { enumerable: true, get: function () { return ns_1.NS; } });
var porkbun_urlfwd_1 = require("./porkbun-urlfwd");
Object.defineProperty(exports, "PORKBUN_URLFWD", { enumerable: true, get: function () { return porkbun_urlfwd_1.PORKBUN_URLFWD; } });
var ptr_1 = require("./ptr");
Object.defineProperty(exports, "PTR", { enumerable: true, get: function () { return ptr_1.PTR; } });
var r53_alias_1 = require("./r53-alias");
Object.defineProperty(exports, "R53_ALIAS", { enumerable: true, get: function () { return r53_alias_1.R53_ALIAS; } });
var soa_1 = require("./soa");
Object.defineProperty(exports, "SOA", { enumerable: true, get: function () { return soa_1.SOA; } });
var srv_1 = require("./srv");
Object.defineProperty(exports, "SRV", { enumerable: true, get: function () { return srv_1.SRV; } });
var sshfp_1 = require("./sshfp");
Object.defineProperty(exports, "SSHFP", { enumerable: true, get: function () { return sshfp_1.SSHFP; } });
var svcb_1 = require("./svcb");
Object.defineProperty(exports, "SVCB", { enumerable: true, get: function () { return svcb_1.SVCB; } });
var tlsa_1 = require("./tlsa");
Object.defineProperty(exports, "TLSA", { enumerable: true, get: function () { return tlsa_1.TLSA; } });
var txt_1 = require("./txt");
Object.defineProperty(exports, "TXT", { enumerable: true, get: function () { return txt_1.TXT; } });
var url_1 = require("./url");
Object.defineProperty(exports, "URL", { enumerable: true, get: function () { return url_1.URL; } });
var url301_1 = require("./url301");
Object.defineProperty(exports, "URL301", { enumerable: true, get: function () { return url301_1.URL301; } });
var ignore_1 = require("./ignore");
Object.defineProperty(exports, "IGNORE", { enumerable: true, get: function () { return ignore_1.IGNORE; } });
