name: CI
on:
  pull_request:
  workflow_dispatch:
  
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v2
        with:
          version: v2025.5.5
          install: true
          cache: true
          experimental: true
          log_level: debug

      - name: install dependency
        run: npm install
        working-directory: '@cdk-dnscontrol'

      - name: run ci
        run: mise run ci
