name: CI
on:
  pull_request:
  workflow_dispatch:
  
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: install dependency
        run: npm install
        working-directory: '@cdk-dnscontrol'
      
      - name: use Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'
      
      - name: install task
        run: go install github.com/go-task/task/v3/cmd/task@latest
        working-directory: '@cdk-dnscontrol'

      - name: install golangci-lint
        uses: go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.0.0

      - name: run ci
        run: task ci
