name: Deploy Docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: jdx/mise-action@v2
        with:
          version: v2025.5.5
          install: true
          cache: true
          experimental: true
          log_level: debug

      - name: Install mkdocs
        run: mise run install-mkdocs

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
